services:
  tracklife:
    build: .
    container_name: tracklife
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://api.tracklife.test
      NEXT_PUBLIC_APP_URL: http://app.tracklife.test
    volumes:
      - .:/app
      - tracklife_node_modules:/app/node_modules
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tracklife.rule=Host(`app.tracklife.test`) || Host(`tracklife.test`)"
      - "traefik.http.routers.tracklife.entrypoints=web"
      - "traefik.http.services.tracklife.loadbalancer.server.port=3000"

volumes:
  tracklife_node_modules:

networks:
  traefik_net:
    external: true
